function coarsenFB(obj,l)

Ff = sum( ...
    obj.Levels(l).Results.p .* ...
    obj.Levels(l).Domain.dx .* ...
    obj.Levels(l).Domain.dy, ...
    "all");

Fc = sum( ...
    obj.Levels(l-1).Results.p .* ...
    obj.Levels(l-1).Domain.dx .* ...
    obj.Levels(l-1).Domain.dy, ...
    "all");

obj.Levels(l-1).fb = obj.Levels(l).fb + Ff - Fc;

end

